apiVersion: v1
kind: Secret
metadata:
  name: {{ include "seamware-ckan.appSecretName" . }}
  labels:
    {{- include "seamware-ckan.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password | quote }}
  CKAN_DB_PASSWORD: {{ .Values.ckan.database.password | quote }}
  DATASTORE_READONLY_PASSWORD: {{ .Values.ckan.database.datastoreReadOnlyPassword | quote }}
  CKAN_SQLALCHEMY_URL: {{ include "seamware-ckan.sqlalchemyURL" . | quote }}
  CKAN_DATASTORE_WRITE_URL: {{ include "seamware-ckan.datastoreWriteURL" . | quote }}
  CKAN_DATASTORE_READ_URL: {{ include "seamware-ckan.datastoreReadURL" . | quote }}
  CKAN___SECRET_KEY: {{ .Values.ckan.security.secretKey | quote }}
  CKAN___WTF_CSRF_SECRET_KEY: {{ .Values.ckan.security.wtfCsrfSecretKey | quote }}
  CKAN___BEAKER__SESSION__SECRET: {{ .Values.ckan.security.beakerSessionSecret | quote }}
  CKAN___API_TOKEN__JWT__ENCODE__SECRET: {{ .Values.ckan.security.apiTokenJwtEncodeSecret | quote }}
  CKAN___API_TOKEN__JWT__DECODE__SECRET: {{ .Values.ckan.security.apiTokenJwtDecodeSecret | quote }}
  CKAN_SYSADMIN_PASSWORD: {{ .Values.ckan.sysadmin.password | quote }}
  CKAN_SMTP_PASSWORD: {{ .Values.ckan.smtp.password | quote }}
  CKANEXT_OIDC4VC_CLIENT_SECRET: {{ .Values.ckan.oidc4vc.clientSecret | quote }}
  {{- range $key, $value := .Values.ckan.extraSecretEnv }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
