apiVersion: v1
kind: Service
metadata:
  name: {{ include "seamware-ckan.webName" . }}
  labels:
    {{- include "seamware-ckan.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "seamware-ckan.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
---
{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "seamware-ckan.postgresql.name" . }}
  labels:
    {{- include "seamware-ckan.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "seamware-ckan.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
  ports:
    - name: postgresql
      port: {{ .Values.postgresql.port }}
      targetPort: postgresql
{{- end }}
---
{{- if .Values.solr.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "seamware-ckan.solr.name" . }}
  labels:
    {{- include "seamware-ckan.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "seamware-ckan.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: solr
  ports:
    - name: http
      port: {{ .Values.solr.port }}
      targetPort: http
{{- end }}
---
{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "seamware-ckan.redis.name" . }}
  labels:
    {{- include "seamware-ckan.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "seamware-ckan.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
  ports:
    - name: redis
      port: {{ .Values.redis.port }}
      targetPort: redis
{{- end }}
